### ISSUE TITLE
[Bug] Websites not in lists randomly get colored.

### ISSUE THREAD

**Issue by TFWol** [Yanorei32/GSI4D#10]
I like the idea of your script. Some things are broken though.

Various websites not in a defined list are getting colored. Also bleed-through.

![image](https://github.com/yanorei32/GSI4D/assets/9045213/398005da-9ab6-43b2-aa39-ecbe6e21ea37)

**Comment by yanorei32** [comment]
I was trying to reproduce and fix this problem, but I could not reproduce this problem in my environment.
This problem may related to the DOM tree structure that was changed by Google's A/B test.

I need the new DOM tree structure information to fix it.
I can fix it if it reproduces in my environment...

Thanks reporting. and I'm sorry.
I'll continue trying to reproduce it.

![image](https://github.com/yanorei32/GSI4D/assets/11992915/970c5755-9a1a-474f-9fc9-5ce07ccdf06b)

**Comment by TFWol** [comment]
Thanks for taking a look.
Yeah, it looks like it happens when the page has various "smart" results added in.

**Comment by TFWol** [comment]
I was able to fix this issue while trying to fix a different problem.
Submitted a Pull request 😃 

![image](https://github.com/yanorei32/GSI4D/assets/9045213/07ec8a5c-cf9e-47c0-8de7-9d427f6849d2)

**Comment by yanorei32** [comment]
Thank you for the nice fixes!
